language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "bogalvan-github"
    token:
      secure: "b7244c15e59eed160496e6aa5b05931a6e60eba1"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'