language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "bogalvan-github"
    token:
      secure: "09f095e1bd45b1b18c0f432a666f9c9b24081e48"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
      